---

version: '3.7'
services:

  nginx:
    build:
      context: "./nginx/"
      dockerfile: "Dockerfile"

  fastapi:
    build:
      args:
        DEPLOY_ENV: ${DEPLOY_ENV}
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
      context: "./fastapi/"
      dockerfile: "docker/Dockerfile"

  db:
    build:
      context: "./db/"
      dockerfile: "Dockerfile"
