"""add process table

Revision ID: 36cd96f7dc3c
Revises: 06aa198ec72c
Create Date: 2020-11-03 11:49:11.244587

"""
from alembic import op
import fastapi_utils.guid_type
import geoalchemy2.types
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36cd96f7dc3c'
down_revision = '06aa198ec72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('returns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deprecated', sa.Boolean(), nullable=True),
    sa.Column('experimental', sa.Boolean(), nullable=True),
    sa.Column('exceptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('process_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process')),
    sa.UniqueConstraint('id', name=op.f('uq_process_id')),
    schema='openeo_dev'
    )
    op.create_index('idx_process_categories', 'process', ['categories'], unique=False, schema='openeo_dev', postgresql_using='gin')
    op.create_index('idx_process_description', 'process', ['description'], unique=False, schema='openeo_dev', postgresql_using='btree')
    op.create_index('idx_process_identifier', 'process', ['id'], unique=False, schema='openeo_dev', postgresql_using='btree')
    op.create_index('idx_process_parameters', 'process', ['parameters'], unique=False, schema='openeo_dev', postgresql_using='gin')
    op.create_index('idx_process_returns', 'process', ['returns'], unique=False, schema='openeo_dev', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_process_returns', table_name='process', schema='openeo_dev')
    op.drop_index('idx_process_parameters', table_name='process', schema='openeo_dev')
    op.drop_index('idx_process_identifier', table_name='process', schema='openeo_dev')
    op.drop_index('idx_process_description', table_name='process', schema='openeo_dev')
    op.drop_index('idx_process_categories', table_name='process', schema='openeo_dev')
    op.drop_table('process', schema='openeo_dev')
    # ### end Alembic commands ###
